/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComandaRouteImport } from './routes/comanda'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaRoute = ComandaRouteImport.update({
  id: '/comanda',
  path: '/comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comanda': typeof ComandaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comanda': typeof ComandaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comanda': typeof ComandaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comanda' | '/sitemap.xml' | '/produs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comanda' | '/sitemap.xml' | '/produs/$slug'
  id: '__root__' | '/' | '/comanda' | '/sitemap.xml' | '/produs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComandaRoute: typeof ComandaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda': {
      id: '/comanda'
      path: '/comanda'
      fullPath: '/comanda'
      preLoaderRoute: typeof ComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComandaRoute: ComandaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdusSlugRoute: ProdusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
