/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AbonamenteRouteImport } from './routes/abonamente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComandaRouteImport } from './routes/comanda'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EvenimenteRouteImport } from './routes/evenimente'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonamenteRoute = AbonamenteRouteImport.update({
  id: '/abonamente',
  path: '/abonamente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaRoute = ComandaRouteImport.update({
  id: '/comanda',
  path: '/comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenimenteRoute = EvenimenteRouteImport.update({
  id: '/evenimente',
  path: '/evenimente',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonamente': typeof AbonamenteRoute
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/evenimente': typeof EvenimenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonamente': typeof AbonamenteRoute
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/evenimente': typeof EvenimenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/abonamente': typeof AbonamenteRoute
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/evenimente': typeof EvenimenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/produs/$slug': typeof ProdusSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonamente'
    | '/auth'
    | '/comanda'
    | '/confidentialitate'
    | '/cookies'
    | '/evenimente'
    | '/sitemap.xml'
    | '/termeni'
    | '/admin'
    | '/produs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonamente'
    | '/auth'
    | '/comanda'
    | '/confidentialitate'
    | '/cookies'
    | '/evenimente'
    | '/sitemap.xml'
    | '/termeni'
    | '/admin'
    | '/produs/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/abonamente'
    | '/auth'
    | '/comanda'
    | '/confidentialitate'
    | '/cookies'
    | '/evenimente'
    | '/sitemap.xml'
    | '/termeni'
    | '/_authenticated/admin'
    | '/produs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbonamenteRoute: typeof AbonamenteRoute
  AuthRoute: typeof AuthRoute
  ComandaRoute: typeof ComandaRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  CookiesRoute: typeof CookiesRoute
  EvenimenteRoute: typeof EvenimenteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniRoute: typeof TermeniRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonamente': {
      id: '/abonamente'
      path: '/abonamente'
      fullPath: '/abonamente'
      preLoaderRoute: typeof AbonamenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda': {
      id: '/comanda'
      path: '/comanda'
      fullPath: '/comanda'
      preLoaderRoute: typeof ComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenimente': {
      id: '/evenimente'
      path: '/evenimente'
      fullPath: '/evenimente'
      preLoaderRoute: typeof EvenimenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbonamenteRoute: AbonamenteRoute,
  AuthRoute: AuthRoute,
  ComandaRoute: ComandaRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  CookiesRoute: CookiesRoute,
  EvenimenteRoute: EvenimenteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniRoute: TermeniRoute,
  ProdusSlugRoute: ProdusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
